mode: 'train' # 'eval' 'test' 'finetune'


wave:
  sr: 44100
  window_size: 1024
  hop_length: 512
  mel_bins: 64
  fmin: 50
  fmax: 14000


decoder:
  decoder_only: Yes
  nhead: 4
  nhid: 128
  nlayers: 2
  dropout: 0.2
  dim_feedforward: 2048
  activation: 'gelu'


encoder:
  model: 'Cnn10'
  freeze: No
  pretrained: Yes


dcasenet:
  use: Yes
  path: 'pretrained_models/encoder/best_SED.pt'


word_embedding:
  pretrained: No
  freeze: Yes


data:
  type: 'clotho'  # 'clotho' 'audiocaps'
  input_field_name: 'audio_data'  # 'feature'
  batch_size: 32
  num_workers: 8
  load_into_memory: No


training:
  mixup: No
  alpha: 0.2
  label_smoothing: No
  keyword: No
  spec_augmentation: Yes
  epochs: 30
  lr: !!float 1e-3
  clip_grad: 2
  seed: 20


finetune:
  audiocap: No
  lr: !!float 1e-4
  model: "outputs/audiocaps/audio_exp1_Cnn10_random/model/model_30.pt"
  epochs: 20


path:
  clotho:
    words_list: 'data/pickles/words_list.p'
    words_freq: 'data/pickles/words_freq.p' 
  audiocaps:
    words_list: 'audiocaps/pickles/words_list.p'
    words_freq: 'audiocaps/pickles/words_freq.p' 
  encoder: 'pretrained_models/encoder/'
  word2vec: 'pretrained_models/word2vec/w2v.model'
  model: 'outputs/submission1/audio_exp_random_mixture/model/best_model.pt'


rl:
  mode: 'greedy'  # 'beam'
  epochs: 25
  model: "outputs/spec/audio_exp1_Cnn10_random_mixture/modelmodel_29.pt"
  lr: !!float 1e-5